spring:
  application:
    name: claro-customer-ms
  rabbitmq:
    host: ${RABBITMQ_HOST:undefined}
    port: ${RABBITMQ_PORT:0000}
    username: ${RABBITMQ_USERNAME:undefined}
    password: ${RABBITMQ_PASSWORD:undefined}
  security:
    oauth2:
      resource:
        filter-order: 3